### Linear regression

In [2]:
import numpy as np
import pandas as pd 
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [3]:
diabetes =datasets.load_diabetes()

In [4]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [5]:
x =diabetes.data
y = diabetes.target

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3,random_state =2)

In [12]:
lasso =linear_model.Lasso()

In [14]:
scores =cross_val_score(lasso, x_train,y_train,cv=3)

scores, scores.mean()

(array([0.2937018 , 0.34188643, 0.3376915 ]), 0.32442657646587153)

In [16]:
lasso.fit(x_train,y_train)

Lasso()

In [18]:
lasso.score(x_test,y_test)

0.3570611452778222

In [20]:
lasso.score(x_train,y_train)

0.36478035566377787

In [22]:
lasso.predict(x_test)

array([154.61805437, 191.85145673, 142.44161176, 128.09415152,
       212.95725163, 189.02667462, 127.40659822, 129.14261234,
       126.62195206, 174.34453603, 162.10108322, 145.99826519,
       154.0817835 , 155.84265002, 223.22433648, 137.07321104,
       179.54702761, 137.72077529, 149.28125932, 131.0263533 ,
       147.14090589, 187.69738304, 148.04446006, 174.34519385,
       141.89702123, 179.61209691, 167.80897684, 135.69185167,
       110.07043299, 201.78568328, 204.11220233, 125.68080814,
       111.24975729, 131.24032383, 185.09172649, 157.25960983,
       158.37946198, 176.18752056, 131.92990711, 179.87242551,
       149.95406132, 139.34303182, 188.09853878, 163.87490291,
       165.28272532, 153.33313928, 152.37801856, 222.0862324 ,
       123.25626095, 173.86615528, 200.84480917, 138.44328311,
       139.12971451, 129.01067284, 175.70160362, 115.46216824,
       135.54054683, 111.43925924, 138.89062129, 151.26082373,
       157.90865947, 160.19278253, 130.28540366, 184.55

In [24]:
lasso =linear_model.Ridge()

In [26]:
scores =cross_val_score(lasso, x_train,y_train,cv=3)

scores, scores.mean()

(array([0.35948739, 0.34344748, 0.3754204 ]), 0.3594517580089949)

In [27]:
lasso.fit(x_train,y_train)

Ridge()

In [30]:
lasso.score(x_test,y_test)

0.40285905799901944

In [32]:
lasso.score(x_train,y_train)

0.4283627636353473

In [34]:
lasso.predict(x_test)

array([153.97395026, 182.29555212, 143.75610355, 120.24101832,
       221.70601185, 214.5138471 , 116.93024215, 124.19636199,
       104.32980572, 177.57367723, 161.23224327, 169.10262194,
       178.72170479, 154.47065753, 226.80961006, 106.09482145,
       178.30218002, 143.23526352, 144.08601008, 142.58627147,
       132.04732887, 185.45570239, 169.18457967, 173.383447  ,
       132.08154633, 207.43383519, 183.2814241 , 132.35737662,
        83.74538475, 225.21444266, 219.93365519, 129.95371741,
        95.10455405, 122.04130414, 189.92287416, 165.9508075 ,
       164.12088139, 188.45036267, 124.38451973, 218.1400407 ,
       136.36253716, 132.65612374, 179.31535426, 181.78937494,
       163.70203783, 149.46963958, 168.7720102 , 249.53674688,
       127.27985058, 185.72399988, 215.24393954, 132.54241488,
       145.7140202 , 154.87760339, 180.8353183 , 124.761818  ,
       161.52360899, 102.6915938 , 159.13363438, 144.48164153,
       162.19012929, 168.43221385, 120.97091768, 192.30

### Linear Regression

In [37]:
diabetes =datasets.load_diabetes()

In [39]:
x =diabetes.data
y = diabetes.target

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3,random_state =2)

In [43]:
ln = LinearRegression()

In [45]:
scores =cross_val_score(lasso, x_train,y_train,cv=3)

scores, scores.mean()

(array([0.35948739, 0.34344748, 0.3754204 ]), 0.3594517580089949)

In [47]:
ln.fit(x_train, y_train)

LinearRegression()

In [48]:
ln.score(x_test,y_test)

0.5012577617513011

In [50]:
ln.score(x_train,y_train)

0.5199919736819347

In [52]:
ln.predict(x_test)

array([153.24339813, 204.26381611, 125.2186365 , 108.21667526,
       256.03550591, 253.23544752, 117.4202117 , 120.55540989,
        95.78875291, 190.06933209, 143.96826124, 177.3044276 ,
       180.06531677, 135.90401855, 287.68340639,  90.25812623,
       212.08917873, 160.21385468, 134.88648137, 121.37205755,
       138.57197801, 168.29864017, 163.21775002, 176.29678184,
       130.77619054, 226.7368069 , 195.60499655, 101.68244487,
        48.13342929, 240.05165989, 246.46333621, 120.1810255 ,
        71.53033687,  97.44323664, 202.47894902, 171.05276648,
       159.90270046, 196.2299122 , 114.72108211, 242.26746679,
       134.7889607 , 119.20956875, 193.3281822 , 199.58553549,
       172.21156859, 151.01230884, 164.62045494, 281.50164269,
       104.14975515, 170.37710519, 254.31387022, 133.68316135,
       154.97446189, 114.95733174, 192.56997469,  82.74618773,
       131.98867054,  71.11857074, 161.0751863 , 161.06645075,
       169.80610128, 158.39872604,  96.40547337, 238.32

### GradientBoostingRegressor

In [56]:
import numpy as np
from sklearn import datasets 
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [58]:
diabetes =datasets.load_diabetes()

In [60]:
x = diabetes.data
y = diabetes.target

In [62]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [64]:
gbr= GradientBoostingRegressor(n_estimators=100, learning_rate=0.1,max_depth=3, random_state=42)

In [66]:
cv = cross_val_score(gbr,x_train,y_train,cv=3)
cv, cv.mean()

(array([0.24249468, 0.47115646, 0.32056367]), 0.3447382708686512)

In [67]:
gbr.fit(x_train, y_train)

GradientBoostingRegressor(random_state=42)

In [68]:
gbr.score(x_test,y_test)

0.4310349361457486

In [71]:
gbr.predict(x_test)

array([165.4746526 , 189.9314141 , 149.64521758, 261.70047229,
       122.56366241, 162.21318548, 248.51910059, 206.11208684,
       143.14608505, 138.09484357,  96.25612442, 201.34406593,
        82.86313838, 237.23360679, 113.51509343, 111.34866975,
       224.26256289, 258.38379431, 198.82461181, 223.16445698,
       175.9521073 , 105.98362415,  68.72355121, 199.73977447,
       151.71944593, 188.234209  , 216.12980178, 190.30050611,
        81.85065256, 113.14813588, 196.69758256, 120.68667771,
       154.04549662, 191.66858885, 131.68819221, 177.52306107,
       112.30456211, 109.59646305, 179.46152047,  75.28681943,
        65.01886663,  88.31753286, 195.41389509, 178.20594403,
       166.67974085,  79.26718402,  97.90408266, 114.96191505,
        69.24642092, 172.76735592, 127.85441568,  72.98229975,
       154.23440817, 111.24730613, 220.29902352, 148.50427047,
        96.96739251, 212.44451333,  93.55788885,  87.4229848 ,
       178.06495817, 188.86572393, 117.77557316,  80.30

### Normalizer

In [74]:
x =diabetes.data
y = diabetes.target

In [77]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state = 42)

In [78]:
scaler = StandardScaler()
x_train_scaled =scaler.fit_transform(x_train)
x_test_scaled =scaler.transform(x_test)

In [81]:
x_train

array([[ 0.03081083,  0.05068012,  0.03259528, ...,  0.03430886,
         0.06301517,  0.00306441],
       [ 0.07440129, -0.04464164,  0.08540807, ..., -0.00259226,
         0.00620674,  0.08590655],
       [-0.05637009,  0.05068012, -0.0105172 , ...,  0.03430886,
         0.02060939,  0.0569118 ],
       ...,
       [ 0.03081083, -0.04464164, -0.02021751, ..., -0.03949338,
        -0.01090325, -0.0010777 ],
       [-0.01277963, -0.04464164, -0.02345095, ..., -0.00259226,
        -0.03845972, -0.03835666],
       [-0.09269548, -0.04464164,  0.02828403, ..., -0.03949338,
        -0.00514219, -0.0010777 ]])

In [83]:
x_train_scaled

array([[ 6.42054387e-01,  1.05661647e+00,  6.19059528e-01, ...,
         6.76301514e-01,  1.27560982e+00, -2.79646760e-04],
       [ 1.58492079e+00, -9.46417203e-01,  1.71984406e+00, ...,
        -8.48887236e-02,  8.94884476e-02,  1.72793733e+00],
       [-1.24367842e+00,  1.05661647e+00, -2.79540092e-01, ...,
         6.76301514e-01,  3.90205997e-01,  1.12306139e+00],
       ...,
       [ 6.42054387e-01, -9.46417203e-01, -4.81725006e-01, ...,
        -8.46078961e-01, -2.67756388e-01, -8.66904956e-02],
       [-3.00812016e-01, -9.46417203e-01, -5.49119978e-01, ...,
        -8.48887236e-02, -8.43116611e-01, -8.64388135e-01],
       [-2.02940042e+00, -9.46417203e-01,  5.29199566e-01, ...,
        -8.46078961e-01, -1.47469368e-01, -8.66904956e-02]])

In [85]:
# Option 2: Scale using MinMaxScaler
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [87]:
gbr = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1,max_depth=3,random_state=42)

In [89]:
cs = cross_val_score(gbr, x_train_scaled, y_train, cv=3)
cs, cs.mean()

(array([0.25030073, 0.47109784, 0.32802928]), 0.34980928053109955)

In [90]:
gbr.fit(x_train_scaled,y_train)

GradientBoostingRegressor(random_state=42)

In [92]:
gbr.score(x_test_scaled, y_test)

0.43126655015263626

In [94]:
gbr.predict(x_test)

array([101.99528746,  96.95588088, 112.30464401, 110.83536947,
       118.77249724, 118.77249724, 123.45339562, 110.83536947,
        91.95730218, 118.77249724, 118.77249724,  91.95730218,
        98.42515542,  98.4251594 ,  98.42515542,  98.42515542,
       105.63095689, 105.63095689,  96.95588088,  93.22074682,
        91.95730218, 118.77249724,  98.42515542,  98.4251594 ,
        98.42515542,  96.95588088,  91.7514683 ,  96.95588088,
        98.42515542, 118.77249724, 101.1578746 , 105.78216386,
        99.31431062,  90.48802764, 112.30464401, 105.63095689,
        91.95730218, 112.30464401, 112.30464401,  98.42515542,
        98.42515542,  96.95588088,  96.95588088,  99.31431062,
       103.47836103, 118.72289736,  98.42515542,  98.37555553,
        98.42515542,  91.95730218,  93.22074284,  98.42515542,
       105.78216386,  98.42515542, 107.06786152,  93.22074284,
       118.77249724,  85.28361506,  98.42515542,  98.37555553,
       112.30464401,  91.95730218,  93.22074284,  97.53